(
"ulludllrrlddldud",
[
"xxxxxxxxxxxxxxxxxxxx",
"x------x---x--x----x",
"x---xg-xx---x----x-x",
"x--------xx--------x",
"xx----------x--xx--x",
"x---x--x-x--------xx",
"xx--x-----x-xx--x--x",
"x----------x----x-xx",
"xxx--xxx--xxx------x",
"x--x---------xxxxx3x",
"x-------x-------x--x",
"x-x--x--x-xx---x--xx",
"x2xx----x--------x-x",
"x-1----xx-----x----x",
"xxxxxxxxxxxxxxxxxxxx"
]
)
